# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
  default:
    - step:
        caches:
          - node
        script: # Modify the commands below to build your repository.
          - npm install
          - npm run build
        artifacts:
          - build/**
    - step:
        name: SFTP Deplot
        deployment: production
        script:
          - pipe: atlassian/sftp-deploy:0.5.6
            variables:
              USER: $SFTP_USER
              SERVER: $SFTP_SERVER
              REMOTE_PATH: '~/'
              LOCAL_PATH: 'build/*'
              PASSWORD: $SFTP_PASSWORD

